/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cddipfbiqnxouvgsndly"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkZGlwZmJpcW54b3V2Z3NuZGx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAyNTk1NjMsImV4cCI6MjA4NTgzNTU2M30.v5kxc-jLeAra-aXgXxNAm2JKsbOTU5miWtkB1XPGdLA"