#!/usr/bin/env python3
"""Generates docs/design/screen-matrix.json and SCREEN_COVERAGE_MATRIX.md from docs/design/figma-frames.json
and scripts/screen_matrix_data.py. Fails when a frame is unclassified."""
import json, sys, collections
sys.path.insert(0, "scripts")
from screen_matrix_data import C, L, COMPONENTS

frames = json.load(open("docs/design/figma-frames.json"))
by_name = {n: i for i, n in frames if n in C}
rows, errors = [], []
for fid, name in frames:
    r = dict(id=fid, name=name)
    if name.startswith("WALKTHROUGH / "):
        canon = name[len("WALKTHROUGH / "):]
        r.update(status="DUPLICATE", route="-", component="-", functional="-", vercel="-",
                 note=f"Prototype-flow copy of {by_name.get(canon, '?')} ({canon})")
        if canon not in C: errors.append(("walkthrough without canonical", fid, name))
    elif "PAGE NOTES" in name or name.startswith("13 — PROTOTYPE FLOWS") or name.startswith("Keyboard-active:"):
        r.update(status="NOTE", route="-", component="-", functional="-", vercel="-", note="Design notes / prototype wiring, not a screen")
    elif name in C:
        s, route, comp, fn, vx, note = C[name]
        r.update(status=s, route=route, component=comp, functional=fn, vercel=vx, note=note)
    elif fid.startswith("248:") or fid in ("179:2", "424:97"):
        r.update(status="COMPONENT", route="-", component=COMPONENTS.get(name, "?"), functional="yes", vercel="yes", note="Design-system component, not a screen")
        if name not in COMPONENTS: errors.append(("component unmapped", fid, name))
    elif name in L:
        s, canon, note = L[name]
        route = component = "-"
        if s in ("IMPLEMENTED", "STATE", "PARTIAL", "COMPONENT"): component = note; note = "Legacy single-screen frame"
        if canon: note = f"{note} (canonical: {by_name.get(canon, '?')} {canon})"
        r.update(status=s, route=route, component=component, functional="yes" if s in ("IMPLEMENTED", "STATE") else "-", vercel="yes" if s in ("IMPLEMENTED", "STATE") else "-", note=note)
        if canon and canon not in C: errors.append(("legacy canonical missing", fid, canon))
    elif "Concept" in name:
        r.update(status="EXCLUDED", route="-", component="-", functional="-", vercel="-", note="Concept frame: exploratory feature labelled Concept in Figma, no product decision")
    else:
        errors.append(("unclassified", fid, name)); continue
    rows.append(r)
if errors:
    for e in errors: print("ERROR", e)
    sys.exit(1)
json.dump(rows, open("docs/design/screen-matrix.json", "w"), indent=1, ensure_ascii=False)
cnt = collections.Counter(r["status"] for r in rows)
md = ["# Screen coverage matrix (Figma ↔ application)", "",
      "Generated by `python3 scripts/gen_screen_matrix.py` from `scripts/screen_matrix_data.py`. Source: Figma file `8WMBpUhanDkUjodZYolyDT`, canvas `280:15`, all %d top-level frames." % len(rows), "",
      "Rule: Vercel is the foundation. A frame is IMPLEMENTED only when it exists in the app with working navigation. Canvas coordinates are ignored.", "",
      "## Summary", "", "| Status | Frames |", "|---|---|"]
for s in ["IMPLEMENTED", "PARTIAL", "MISSING", "STATE", "RESPONSIVE_VARIANT", "DUPLICATE", "OUTDATED", "COMPONENT", "NOTE", "EXCLUDED"]:
    md.append(f"| {s} | {cnt.get(s,0)} |")
md += ["", "## Matrix", "", "| Figma screen | Node | Route | Code component | Status | Functional? | Matches Vercel UX? | Action / reason |", "|---|---|---|---|---|---|---|---|"]
order = {"MISSING": 0, "PARTIAL": 1}
for r in sorted(rows, key=lambda r: (order.get(r["status"], 2), r["name"])):
    esc = lambda x: str(x).replace("|", "\\|")
    md.append(f"| {esc(r['name'])} | {r['id']} | {esc(r['route'])} | {esc(r['component'])} | {r['status']} | {r['functional']} | {r['vercel']} | {esc(r['note'])} |")
open("docs/design/SCREEN_COVERAGE_MATRIX.md", "w").write("\n".join(md) + "\n")
print(dict(cnt), len(rows))
