"""Source of truth for docs/design/SCREEN_COVERAGE_MATRIX.md and screen-matrix.json.
Run: python3 scripts/gen_screen_matrix.py
Statuses: IMPLEMENTED, PARTIAL, MISSING, DUPLICATE, OUTDATED, COMPONENT, RESPONSIVE_VARIANT, STATE, NOTE, EXCLUDED.
Every EXCLUDED, OUTDATED and DUPLICATE row carries a reason. MISSING must be empty before the work is declared done.
"""
# canonical screens: name -> (status, route, component, functional, vercel_ux_match, action_or_reason)
Y = "yes"
C = {
# ---- ONBOARDING
"ONBOARDING / Splash / Default / Mobile": ("IMPLEMENTED", "#/ (onboarding entry)", "OnboardingSystem (entry)", Y, Y, ""),
"ONBOARDING / Language Selection / Default / Mobile": ("IMPLEMENTED", "#/ (onboarding)", "LanguageSelectionScreen", Y, Y, ""),
"ONBOARDING / Introduction / Default / Mobile": ("IMPLEMENTED", "#/ (onboarding purpose)", "OnboardingPurpose", Y, Y, ""),
"ONBOARDING / Intent / Default / Mobile": ("IMPLEMENTED", "#/ (onboarding intent)", "OnboardingSystem IntentStep", Y, Y, ""),
"ONBOARDING / Role / Default / Mobile": ("IMPLEMENTED", "#/ (onboarding role)", "OnboardingSystem RoleStep", Y, Y, ""),
"ONBOARDING / Personalization / Default / Mobile": ("IMPLEMENTED", "#/ (onboarding presence)", "OnboardingSystem PresenceStep", Y, Y, "Presence step carries the personalization choices"),
"ONBOARDING / Accessibility / Default / Mobile": ("IMPLEMENTED", "#/ (onboarding accessibility)", "OnboardingAccessibility", Y, Y, ""),
"ONBOARDING / Sign Up / Default / Mobile": ("IMPLEMENTED", "#/ (onboarding account)", "OnboardingSystem AccountStep", Y, Y, ""),
"ONBOARDING / Sign In / Default / Mobile": ("IMPLEMENTED", "#/ (onboarding account, sign-in mode)", "OnboardingSystem AccountStep", Y, Y, ""),
"ONBOARDING / Email Verification / OTP / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Needs a configured Supabase project (verifyOtp); it is rendered only when the backend flag is on, per the no-dead-buttons rule. Tracked in docs/release/RESTORE_SUPABASE.md"),
"ONBOARDING / Forgot Password / Default / Mobile": ("IMPLEMENTED", "#/ (account, recovery mode)", "OnboardingSystem AccountStep", Y, Y, ""),
"ONBOARDING / Reset Password / Default / Mobile": ("IMPLEMENTED", "#/reset-password/:token", "ResetPasswordScreen", Y, Y, ""),
"ONBOARDING / Authentication Failed / Error / Mobile": ("STATE", "#/ (account)", "AccountStep error text (WRONG_CREDENTIALS_MESSAGE)", Y, Y, "State of Sign In"),
"ONBOARDING / Session Expired / Default / Mobile": ("STATE", "#/ (account)", "AccountStep session-expired Banner", Y, Y, "State of Sign In"),
"ONBOARDING / Offline Auth / Default / Mobile": ("STATE", "#/ (account)", "AccountStep offline Banner", Y, Y, "State of Sign In"),
"ONBOARDING / Completion / Mobile": ("IMPLEMENTED", "#/ (onboarding threshold)", "OnboardingSystem ThresholdStep", Y, Y, ""),
"AUTH / Sign In · Keyboard Active / Mobile": ("STATE", "#/ (account)", "AccountStep", Y, Y, "Keyboard state of Sign In; the form scrolls above the keyboard"),
# ---- DISCOVERY
"DISCOVERY / For You / Default / Mobile": ("IMPLEMENTED", "#/for-you", "ForYouScreen + ForYouSections", Y, Y, "Aligned in e17d70c; see FOR_YOU_ALIGNMENT.md"),
"DISCOVERY / For You · Loading / Mobile": ("STATE", "#/for-you", "ForYouScreen (synchronous catalogue; presence rows use useResource skeleton)", Y, Y, "State of For You"),
"DISCOVERY / Explore · Default / Mobile": ("IMPLEMENTED", "#/explore", "ExploreScreen", Y, Y, ""),
"DISCOVERY / Explore · Empty Filter / Mobile": ("STATE", "#/explore", "ExploreScreen empty branch", Y, Y, "State of Explore"),
'DISCOVERY / Search · Landing / Mobile': ('IMPLEMENTED', 'search overlay (#/search)', 'SearchScreen (recent searches, browse by theme)', "yes", "yes", 'Landing shows device-stored recents and themes from the catalogue.'),
"DISCOVERY / Search · Results / Mobile": ("IMPLEMENTED", "#/search", "SearchScreen", Y, Y, ""),
"DISCOVERY / Search · Zero Results / Mobile": ("STATE", "#/search", "SearchScreen 'No stories found'", Y, Y, "State of Search; improve with suggestions"),
'DISCOVERY / Search · Filters Sheet / Mobile': ('IMPLEMENTED', '#/search', 'SearchFiltersSheet', "yes", "yes", 'Language, length and theme filters over the real catalogue.'),
"DISCOVERY / Search · Keyboard Active / Mobile": ("STATE", "#/search", "SearchScreen", Y, Y, "Keyboard state of Search"),
# ---- STORY
"STORY / Story World / Default / Mobile": ("IMPLEMENTED", "#/story/:id", "FeaturedStoryPreview", Y, Y, ""),
"STORY / Chapter Index / Default / Mobile": ("IMPLEMENTED", "chapter-index screen", "ChapterIndexScreen", Y, Y, ""),
"STORY / Audio Player / Playing / Mobile": ("IMPLEMENTED", "story-chapter screen", "StoryChapterScreen + MediaPlayerBar", Y, Y, ""),
'STORY / Audio Player · Captions Active / Mobile': ('IMPLEMENTED', 'story-chapter screen', 'CaptionBar (StoryReaderExtras)', "yes", "yes", 'Captions only for device-voice playback; no invented timing.'),
'STORY / Audio Player · Buffering / Mobile': ('IMPLEMENTED', 'story-chapter screen', 'PlayerAlert (StoryReaderExtras)', "yes", "yes", 'Buffering state shown by the player.'),
'STORY / Audio Player · Playback Failed / Mobile': ('IMPLEMENTED', 'story-chapter screen', 'PlayerAlert (StoryReaderExtras)', "yes", "yes", 'Playback-failed state with retry.'),
'STORY / Transcript / Default / Mobile': ('IMPLEMENTED', 'story-chapter screen', 'TranscriptSheet', "yes", "yes", 'Chapter text paragraphs; no timestamps.'),
"STORY / Context Card Modal / Mobile": ("IMPLEMENTED", "overlay on story-chapter", "ContextCardModal", Y, Y, ""),
'STORY / Story Completion / Default / Mobile': ('IMPLEMENTED', 'story-chapter end', 'StoryCompletion', "yes", "yes", 'Finish button on last chapter; real counts and related stories.'),
"STORY / Video Player / Landscape / Mobile": ("EXCLUDED", "-", "-", "-", "-", "No video content exists in the catalogue (audio and text stories only); landscape player has nothing to play"),
"STORY / Report Content Sheet / Mobile": ("IMPLEMENTED", "sheet on story preview, creator profile", "ReportContentSheet", Y, Y, "Shipped in c5d98f3"),
"STORY / Choice Overlay / Ceremonial / Mobile": ("IMPLEMENTED", "overlay on story-chapter", "BranchingChoiceOverlay", Y, Y, ""),
'STORY / Soft Branching / Perspective Shift / Mobile': ('IMPLEMENTED', 'story-chapter', 'BranchingChoiceOverlay', "yes", "yes", "Same overlay; non-outcome branches use 'Share your perspective' heading (EN/FR/ES), outcome branches 'Your choice matters'."),
"STORY / Branch Map / Creator / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Creator branch-map editor needs a graph authoring tool that the five-step publish flow does not have; branches are authored in the story data. Revisit with the creator tools roadmap"),
"STORY / Community Voices / Panel / Mobile": ("IMPLEMENTED", "panel on story-chapter", "CommunityResponsesPanel", Y, Y, ""),
"STORY / Share Reflection / Modal / Mobile": ("IMPLEMENTED", "modal on story-chapter", "SubmitResponseModal", Y, Y, ""),
"STORY / Share Reflection · Keyboard Active / Mobile": ("STATE", "modal", "SubmitResponseModal", Y, Y, "Keyboard state"),
# ---- LIBRARY
"LIBRARY / Saved · Default / Mobile": ("IMPLEMENTED", "#/library (Saved)", "LibraryScreen", Y, Y, ""),
"LIBRARY / Continue · Default / Mobile": ("IMPLEMENTED", "#/library (In progress)", "LibraryScreen", Y, Y, ""),
"LIBRARY / Downloads · Offline / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Offline reading (E6) waits on the Supabase adapter being live; rules and tests exist (offlineCache.ts), spec in docs/design/OFFLINE_SAVE_SPEC.md. No fake version ships"),
'LIBRARY / Collections · Default / Mobile': ('IMPLEMENTED', '#/library', 'LibraryPanels SavedCollectionsPanel', "yes", "yes", 'Saved collections tab.'),
"LIBRARY / Empty · New User / Mobile": ("STATE", "#/library", "LibraryScreen empty states", Y, Y, "State of Library"),
"LIBRARY / Sync In Progress / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Cross-device sync needs the backend; the demo adapter is device-local so there is nothing to sync"),
'LIBRARY / Following · Default / Mobile': ('IMPLEMENTED', '#/library', 'LibraryPanels FollowingPanel', "yes", "yes", 'Followed creators with optimistic unfollow and rollback.'),
# ---- CREATOR
'CREATOR / Dashboard · Overview / Mobile': ('IMPLEMENTED', '#/profile (creator section)', 'ProfileScreen creator card', "yes", "yes", 'Published and Drafts counts plus Your stories, Notes, New story and Analytics links.'),
'CREATOR / Stories · List / Mobile': ('IMPLEMENTED', '#/creator-stories', 'CreatorStoriesScreen', "yes", "yes", 'Published and Drafts tabs; creator/admin only.'),
"CREATOR / Publish · Step 1 / Mobile": ("IMPLEMENTED", "#/creator-publish", "StoryIntentStep", Y, Y, ""),
"CREATOR / Publish · Step 2 / Mobile": ("IMPLEMENTED", "#/creator-publish", "StoryStructureStep", Y, Y, ""),
"CREATOR / Publish · Step 3 / Mobile": ("IMPLEMENTED", "#/creator-publish", "MediaChaptersStep", Y, Y, ""),
"CREATOR / Publish · Step 4 / Mobile": ("IMPLEMENTED", "#/creator-publish", "ContextAccessibilityStep", Y, Y, ""),
"CREATOR / Publish · Step 5 / Mobile": ("IMPLEMENTED", "#/creator-publish", "PreviewPublishStep", Y, Y, ""),
"CREATOR / Publish · Validation Errors / Mobile": ("STATE", "#/creator-publish", "creator-flow steps (disabled Next + helper text)", Y, Y, "State of publish steps; verify messages"),
"CREATOR / Publish · Processing / Mobile": ("STATE", "#/creator-publish", "PreviewPublishStep publishing state", Y, Y, "State of publish"),
"CREATOR / Publish · In Review / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Stories publish immediately; there is no pre-publication review pipeline to represent. Revisit with moderation policy owner"),
"CREATOR / Publish · Failed / Mobile": ("STATE", "#/creator-publish", "PreviewPublishStep error", Y, Y, "State of publish"),
"CREATOR / Become a Creator · Intro / Mobile": ("IMPLEMENTED", "#/profile (Share Your Story card) -> creator-publish", "ProfileScreen", Y, Y, ""),
"CREATOR / Invite Collaborator · Sheet / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Collaboration needs accounts on a server (invites, permissions); waits on the Supabase backend"),
"TRUST / Content Health Dashboard / Concept · Mobile": ("EXCLUDED", "-", "-", "-", "-", "Concept frame"),
# ---- FUNDING
"FUNDING / Opportunities Hub / Mobile": ("IMPLEMENTED", "#/funding", "FundingScreen", Y, Y, ""),
"FUNDING / Opportunity Detail / Mobile": ("IMPLEMENTED", "#/opportunity/:id", "OpportunityDetailScreen", Y, Y, ""),
'FUNDING / Funding Readiness Profile / Mobile': ('IMPLEMENTED', '#/funding-readiness', 'FundingReadinessScreen', "yes", "yes", 'Self-ticked checklist, no score or verdict; stored on device.'),
"FUNDING / Project Funding / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Project funding and payments are undecided (D-07)"),
'FUNDING / Application · Eligibility Check / Mobile': ('IMPLEMENTED', '#/opportunity/:id', 'OpportunityDetailScreen eligibility self-check', "yes", "yes", "Yes / Not sure / No per listed criterion; result copy is guidance, 'the funder decides'."),
'FUNDING / Application · Workspace / Mobile': ('IMPLEMENTED', '#/opportunity/:id', 'OpportunityDetailScreen checklist, notes, status', "yes", "yes", 'Checklist, private notes (1000 chars) and tracked status; stored with the application.'),
'FUNDING / Application · Review & Submit / Mobile': ('IMPLEMENTED', '#/opportunity/:id', "OpportunityDetailScreen 'Mark as applied'", "yes", "yes", "Submission happens on the funder's site by design; SEEN records 'marked applied by you'."),
'FUNDING / Application · Submitted / Mobile': ('IMPLEMENTED', '#/opportunity/:id', 'OpportunityDetailScreen applied state', "yes", "yes", "Shown as 'Marked as applied', followed by the outcome selector; no funder confirmation is claimed."),
'FUNDING / Application · Under Review / Mobile': ('STATE', '#/opportunity/:id', 'OpportunityDetailScreen outcome selector', "yes", "yes", 'Under Review is a user-recorded outcome labelled "tracked by you"; SEEN receives no funder decisions, so no separate screen.'),
'FUNDING / Application · Shortlisted / Mobile': ('STATE', '#/opportunity/:id', 'OpportunityDetailScreen outcome selector', "yes", "yes", 'Shortlisted is a user-recorded outcome labelled "tracked by you"; SEEN receives no funder decisions, so no separate screen.'),
'FUNDING / Application · Info Requested / Mobile': ('STATE', '#/opportunity/:id', 'OpportunityDetailScreen outcome selector', "yes", "yes", 'Info Requested is a user-recorded outcome labelled "tracked by you"; SEEN receives no funder decisions, so no separate screen.'),
'FUNDING / Application · Approved / Mobile': ('STATE', '#/opportunity/:id', 'OpportunityDetailScreen outcome selector', "yes", "yes", 'Approved is a user-recorded outcome labelled "tracked by you"; SEEN receives no funder decisions, so no separate screen.'),
'FUNDING / Application · Declined / Mobile': ('STATE', '#/opportunity/:id', 'OpportunityDetailScreen outcome selector', "yes", "yes", 'Declined is a user-recorded outcome labelled "tracked by you"; SEEN receives no funder decisions, so no separate screen.'),
'FUNDING / Funding Dashboard / Mobile': ('IMPLEMENTED', '#/funding (My tracker)', 'FundingScreen tracker summary tiles', "yes", "yes", 'Tracked, Applied, Next deadline, Outcomes noted. Status filter chips not added.'),
"FUNDING / CMF Eligibility Checker · Step 2 / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Programme-specific eligibility wizard needs the funder's rules; the generic checklist covers it. No invented eligibility logic"),
# ---- MONETIZATION
"MONETIZATION / Setup · Eligibility / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Payments undecided (D-07)"),
"MONETIZATION / Payment Account Setup / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Payments undecided (D-07)"),
"MONETIZATION / Earnings Overview / Mobile": ("IMPLEMENTED", "#/creator-earnings", "CreatorEarningsScreen", Y, Y, "Demo data, labelled in the screen"),
"MONETIZATION / Revenue Breakdown / Mobile": ("IMPLEMENTED", "#/creator-earnings", "CreatorEarningsScreen breakdown", Y, Y, ""),
"MONETIZATION / Transaction History / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Payments undecided (D-07); no real transactions exist"),
"MONETIZATION / Payout · Pending / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Payments undecided (D-07)"),
"MONETIZATION / Payout · Complete / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Payments undecided (D-07)"),
"MONETIZATION / Payout · Failed / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Payments undecided (D-07)"),
"MONETIZATION / Tax & Payment Information / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Payments undecided (D-07); tax data needs legal review"),
"MONETIZATION / Subscription Setup / Mobile": ("IMPLEMENTED", "#/creator-monetization", "CreatorMonetizationScreen", Y, Y, "Demo"),
# ---- INSTITUTIONS
'INSTITUTIONS / Public Profile / Mobile': ('PARTIAL', '#/collection/:id (institutional)', 'CollectionDetailScreen', "yes", "yes", 'Institutional collections show curator, description and stories. There is no institution entity or profile page; that needs signed partners (D-12).'),
"INSTITUTIONS / Institution Dashboard / Mobile": ("EXCLUDED", "-", "-", "-", "-", "No institutions workspace without signed partners (D-12)"),
"INSTITUTIONS / Collection Management / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Excluded by decision D-12: institutional partner workspaces need signed partner agreements"),
"INSTITUTIONS / Add Story · Metadata & Rights / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Excluded by decision D-12: institutional partner workspaces need signed partner agreements"),
"INSTITUTIONS / Curator Profile / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Excluded by decision D-12: institutional partner workspaces need signed partner agreements"),
"INSTITUTIONS / Team & Permissions / Mobile": ("EXCLUDED", "-", "-", "-", "-", "D-12; needs server roles"),
"INSTITUTIONS / Institutional Analytics / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Excluded by decision D-12: institutional partner workspaces need signed partner agreements"),
"INSTITUTIONS / Partnership / Mobile": ("EXCLUDED", "-", "-", "-", "-", "D-12: never name real organisations as partners without a signed agreement"),
# ---- TRUST
"TRUST / Report Confirmation / Mobile": ("IMPLEMENTED", "sheet success state", "ReportContentSheet (sent)", Y, Y, ""),
"TRUST / Moderation Queue / Mobile": ("IMPLEMENTED", "#/moderation-governance", "ModerationGovernanceSystem Queue + Reports", Y, Y, ""),
"TRUST / Content Review / Mobile": ("IMPLEMENTED", "#/moderation-governance", "ModerationQueue item review (approve, reject, flag)", Y, Y, ""),
"TRUST / Cultural Sensitivity Review / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Needs a named moderation policy owner and reviewers (G4 gate)"),
"TRUST / Moderation Decision / Mobile": ("IMPLEMENTED", "#/moderation-governance", "approve/reject/flag + Audit Log", Y, Y, ""),
"TRUST / Rights Dispute / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Needs a named policy owner and legal process (G4 gate)"),
"TRUST / Appeal · Submitted / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Needs a named policy owner (G4 gate); appeals would otherwise imply an outcome nobody has agreed to deliver"),
"TRUST / Account Enforcement / Mobile": ("EXCLUDED", "-", "-", "-", "-", "Needs a named policy owner and server-side enforcement (G4 gate)"),
"TRUST / Admin · Feature Toggles / Mobile": ("EXCLUDED", "-", "-", "-", "-", "No feature-flag system exists; the only switch is the build-time backend flag (docs/release/BACKEND_CUTOVER.md)"),
# ---- PROFILE
"PROFILE / Public Profile / Mobile": ("IMPLEMENTED", "#/profile", "ProfileScreen", Y, Y, ""),
"PROFILE / Settings Hub / Mobile": ("IMPLEMENTED", "#/settings", "ProfilePreferencesScreen", Y, Y, ""),
"PROFILE / Accessibility Settings / Mobile": ("IMPLEMENTED", "#/settings (Accessibility)", "ProfilePreferencesScreen", Y, Y, ""),
"PROFILE / Notification Settings / Mobile": ("IMPLEMENTED", "#/account (Notifications)", "AccountPrivacyScreen", Y, Y, ""),
"PROFILE / Privacy & Security / Mobile": ("IMPLEMENTED", "#/account", "AccountPrivacyScreen", Y, Y, ""),
"PROFILE / Subscriptions & Billing / Mobile": ("IMPLEMENTED", "#/subscription-management", "SubscriptionManagementScreen", Y, Y, "Demo"),
"PROFILE / Data Controls & Delete Account / Mobile": ("IMPLEMENTED", "#/account (Your data)", "AccountPrivacyScreen", Y, Y, ""),
"PROFILE / Blocked Accounts / Mobile": ("IMPLEMENTED", "#/account (Blocked accounts)", "AccountPrivacyScreen", Y, Y, ""),
"PROFILE / Logout Confirmation / Mobile": ("IMPLEMENTED", "dialog on #/account", "ConfirmDialog", Y, Y, ""),
"PROFILE / About SEEN / Mobile": ("IMPLEMENTED", "#/about", "AboutScreen", Y, Y, ""),
}
# legacy kebab-case frames (older single-screen design round): id-name -> (status, canonical_or_note, route, component, reason/action)
L = {
"chapter-playback": ("OUTDATED", "STORY / Audio Player / Playing / Mobile", "Superseded"),
"track-context": ("OUTDATED", "STORY / Context Card Modal / Mobile", "Superseded"),
"story-builder": ("OUTDATED", "CREATOR / Publish · Step 1 / Mobile", "Superseded by the five-step publish flow"),
"creator-insights": ("EXCLUDED", None, "Creator analytics concept; no analytics collected per creator (privacy-first: no per-person counts)"),
"cmf-step1": ("EXCLUDED", None, "Programme-specific CMF eligibility wizard; see FUNDING / CMF Eligibility Checker"),
"cmf-step2": ("EXCLUDED", None, "Programme-specific CMF eligibility wizard; see FUNDING / CMF Eligibility Checker"),
"cmf-results": ("EXCLUDED", None, "Programme-specific CMF eligibility wizard; see FUNDING / CMF Eligibility Checker"),
"role-elevation": ("EXCLUDED", None, "Role elevation is an admin approval flow that needs server roles; the app records requests only (AuthContext) and says so"),
"pipeda-data": ("DUPLICATE", "PROFILE / Data Controls & Delete Account / Mobile", "Same screen"),
"onboarding-invocation": ("OUTDATED", "ONBOARDING / Introduction / Default / Mobile", "Superseded"),
"admin-governance": ("OUTDATED", "TRUST / Moderation Queue / Mobile", "Superseded"),
"player-reactions": ("EXCLUDED", None, "Public reaction counts conflict with the product principle of no public counts (E1 private notes instead)"),
"language-switcher": ("IMPLEMENTED", None, "LanguageSwitcher + #/settings language group"),
"save-to-collection": ("EXCLUDED", None, "Users cannot create personal collections yet; collections are curated and can be saved as a whole (CollectionsScreen)"),
"explore-cultural-tags": ("DUPLICATE", "DISCOVERY / Explore · Default / Mobile", "Variant of Explore categories"),
"film-player": ("EXCLUDED", None, "No video content in the catalogue"),
"guest-explore": ("EXCLUDED", None, "Guest browsing without an account is not in the current onboarding-gated flow; return-route support exists (safeReturn) for when it is"),
"onboarding-purpose": ("DUPLICATE", "ONBOARDING / Introduction / Default / Mobile", "Same screen"),
"onboarding-presence": ("DUPLICATE", "ONBOARDING / Personalization / Default / Mobile", "Same screen"),
"onboarding-threshold": ("DUPLICATE", "ONBOARDING / Completion / Mobile", "Same screen"),
"admin-analytics": ("OUTDATED", None, "Superseded by the Admin dashboard overview"),
"creator-post-publish": ("IMPLEMENTED", None, "PostPublishSuccess"),
"notifications-screen": ("IMPLEMENTED", None, "NotificationsScreen"),
"opportunities-saved": ("IMPLEMENTED", None, "FundingScreen My tracker"),
"opportunities-calendar": ("EXCLUDED", None, "Calendar view of deadlines; read-time reminders (E5) planned instead, no calendar in scope"),
"opportunities-ai": ("EXCLUDED", None, "AI matching of funding is not built and would need explainability; out of beta scope"),
"error-network": ("STATE", None, "ResourceView offline/error states"),
"notifications-empty": ("STATE", None, "NotificationsScreen empty state"),
"creator-onboarding-step2": ("OUTDATED", "CREATOR / Become a Creator · Intro / Mobile", "Superseded"),
"creator-onboarding-step3": ("OUTDATED", "CREATOR / Become a Creator · Intro / Mobile", "Superseded"),
'edit-profile': ('IMPLEMENTED', None, 'EditProfileScreen at #/edit-profile (name, bio)'),
'change-password': ('IMPLEMENTED', None, 'ChangePasswordScreen at #/change-password'),
"moderation-escalation": ("EXCLUDED", None, "G4 gate: needs a named moderation policy owner"),
"sound-driven-story": ("EXCLUDED", None, "Concept (sound-driven story mode); no decision"),
"audio-layer-control": ("EXCLUDED", None, "Concept; the catalogue has single-track audio"),
"app-update": ("EXCLUDED", None, "Native app update prompt; the native app is paused (D-03) and the web app updates on load"),
"profile-empty": ("STATE", None, "ProfileScreen empty counts"),
"creator-empty": ("STATE", None, "CreatorsPanel/Stories empty states"),
"offline-mode": ("STATE", None, "ResourceView offline banner, auth offline banner"),
"creator-library": ("OUTDATED", "LIBRARY / Saved · Default / Mobile", "Archive-era frame"),
"creator-explore": ("OUTDATED", "DISCOVERY / Explore · Default / Mobile", "Archive-era frame"),
"creator-profile": ("DUPLICATE", "PROFILE / Public Profile / Mobile", "Legacy off-system frame (JetBrains Mono, 56px nav); implemented as CreatorProfileScreen"),
'creator-drafts': ('IMPLEMENTED', None, 'Drafts tab in CreatorStoriesScreen'),
"signup-error": ("STATE", None, "AccountStep error text"),
"signin-error": ("STATE", None, "AccountStep error text"),
'terms-privacy': ('IMPLEMENTED', None, 'LegalScreen at #/legal, clearly marked draft pending counsel review'),
"admin-users": ("IMPLEMENTED", None, "AdminDashboardScreen Users tab"),
"pipeda-delete-confirm": ("IMPLEMENTED", None, "AccountPrivacyScreen delete ConfirmDialog"),
"admin-content": ("OUTDATED", None, "Superseded by the moderation queue"),
"admin-settings": ("IMPLEMENTED", None, "AdminDashboardScreen Settings tab"),
"content-unavailable": ("STATE", None, "ResourceView not_found state"),
"creator-story-preview": ("DUPLICATE", "STORY / Story World / Default / Mobile", "Same screen"),
"notifications-content": ("STATE", None, "NotificationsScreen list"),
"data-export": ("IMPLEMENTED", None, "AccountPrivacyScreen Download my data"),
"permission-denied": ("STATE", None, "App 'Restricted' screen"),
"save-confirmation": ("STATE", None, "Toast 'Saved to your Library'"),
"11-20 — Rate Limited State": ("STATE", None, "AccountStep rate-limit message; note and report rate limits (rate_limited)"),
"06-23 — Creator Analytics Drill-Down": ("EXCLUDED", None, "No per-person analytics by design"),
"archive-home": ("OUTDATED", "DISCOVERY / For You / Default / Mobile", "Archive-era frame"),
"archive-explore": ("OUTDATED", "DISCOVERY / Explore · Default / Mobile", "Archive-era frame"),
"archive-story-entry": ("OUTDATED", "STORY / Story World / Default / Mobile", "Archive-era frame"),
"archive-creator-profile": ("OUTDATED", "PROFILE / Public Profile / Mobile", "Archive-era frame"),
"archive-library": ("OUTDATED", "LIBRARY / Saved · Default / Mobile", "Archive-era frame"),
"13-01 - Cultural Resonance Quiz (A1/A3)": ("EXCLUDED", None, "Concept frame"),
"13-10 — Creator Milestones (E1)": ("EXCLUDED", None, "Concept frame"),
"13-05 — Community Reaction Heatmap (C3)": ("EXCLUDED", None, "Concept frame; conflicts with no public counts"),
"13-15 — Smart Queue (D1)": ("EXCLUDED", None, "Concept frame"),
"13-16 — Listening History Timeline (G1)": ("EXCLUDED", None, "Concept frame"),
"13-08 — Listening Wrapped (D1/D2)": ("EXCLUDED", None, "Concept frame"),
"13-13 — Cultural Sensitivity Review (F1)": ("EXCLUDED", None, "Concept frame; see TRUST / Cultural Sensitivity Review"),
"13-14 — Privacy Dashboard (G3)": ("DUPLICATE", "PROFILE / Privacy & Security / Mobile", "Concept version of the shipped Account and privacy screen"),
"13-11 — Funding Application Tracker (E5)": ("DUPLICATE", "FUNDING / Funding Dashboard / Mobile", "Concept version of the funding tracker"),
"13-07 — Story Completion Celebration (C1)": ("DUPLICATE", "STORY / Story Completion / Default / Mobile", "Concept version of Story Completion"),
"13-09 — Story Impact Dashboard (E3)": ("EXCLUDED", None, "Concept frame; no per-person analytics"),
"13-12 — Content Health Dashboard (F2)": ("EXCLUDED", None, "Concept frame"),
"13-02 — Guest Upgrade Prompt (A2)": ("EXCLUDED", None, "Concept frame; no guest mode"),
"13-06 — Side-by-Side Translation (C4)": ("EXCLUDED", None, "Concept frame; needs translated chapter text pairing, evaluate after Transcript"),
"13-03 — Cultural Map Discovery (B2)": ("EXCLUDED", None, "Concept frame"),
"13-04 — Story Mood Mixer (B1)": ("EXCLUDED", None, "Concept frame"),
"language-selection": ("DUPLICATE", "ONBOARDING / Language Selection / Default / Mobile", "Same screen"),
"onboarding-intent": ("DUPLICATE", "ONBOARDING / Intent / Default / Mobile", "Same screen"),
"onboarding-accessibility": ("DUPLICATE", "ONBOARDING / Accessibility / Default / Mobile", "Same screen"),
"sign-up": ("DUPLICATE", "ONBOARDING / Sign Up / Default / Mobile", "Same screen"),
"sign-in": ("DUPLICATE", "ONBOARDING / Sign In / Default / Mobile", "Same screen"),
"password-recovery": ("DUPLICATE", "ONBOARDING / Forgot Password / Default / Mobile", "Same screen"),
"profile-settings": ("DUPLICATE", "PROFILE / Settings Hub / Mobile", "Same screen"),
"about-screen": ("DUPLICATE", "PROFILE / About SEEN / Mobile", "Same screen"),
"branching-choice": ("DUPLICATE", "STORY / Choice Overlay / Ceremonial / Mobile", "Same screen"),
"branch-map": ("DUPLICATE", "STORY / Branch Map / Creator / Mobile", "Same screen"),
"audio-player": ("DUPLICATE", "STORY / Audio Player / Playing / Mobile", "Same screen"),
"chapter-index": ("DUPLICATE", "STORY / Chapter Index / Default / Mobile", "Same screen"),
"community-responses": ("DUPLICATE", "STORY / Community Voices / Panel / Mobile", "Same screen"),
"submit-response": ("DUPLICATE", "STORY / Share Reflection / Modal / Mobile", "Same screen"),
"creator-onboarding": ("OUTDATED", "CREATOR / Become a Creator · Intro / Mobile", "Superseded"),
"creator-publish": ("DUPLICATE", "CREATOR / Publish · Step 1 / Mobile", "Same flow"),
"moderator-queue": ("DUPLICATE", "TRUST / Moderation Queue / Mobile", "Same screen"),
"moderation-review": ("DUPLICATE", "TRUST / Content Review / Mobile", "Same screen"),
'institutional-collection': ('IMPLEMENTED', None, 'Institutional collection detail is CollectionDetailScreen (badge, curator, stories, save); management is excluded (D-12)'),
"empty-states": ("STATE", None, "StateTemplate across screens"),
"collab-invite": ("EXCLUDED", None, "Needs server accounts"),
"player-captions": ("DUPLICATE", "STORY / Audio Player · Captions Active / Mobile", "Same screen"),
"offline-downloads": ("DUPLICATE", "LIBRARY / Downloads · Offline / Mobile", "Same screen"),
"onboarding-role": ("DUPLICATE", "ONBOARDING / Role / Default / Mobile", "Same screen"),
"creator-dashboard": ("DUPLICATE", "CREATOR / Dashboard · Overview / Mobile", "Same screen"),
"search-screen": ("DUPLICATE", "DISCOVERY / Search · Landing / Mobile", "Same screen"),
"opportunities-hub": ("DUPLICATE", "FUNDING / Opportunities Hub / Mobile", "Same screen"),
"opportunity-detail": ("DUPLICATE", "FUNDING / Opportunity Detail / Mobile", "Same screen"),
"opportunities-funding": ("DUPLICATE", "FUNDING / Opportunities Hub / Mobile", "Same screen"),
"email-verification": ("DUPLICATE", "ONBOARDING / Email Verification / OTP / Mobile", "Same screen"),
"logout-confirmation": ("DUPLICATE", "PROFILE / Logout Confirmation / Mobile", "Same screen"),
"report-content": ("DUPLICATE", "STORY / Report Content Sheet / Mobile", "Same screen"),
"loading-skeleton": ("STATE", None, "Skeleton / SkeletonList (ResourceView)"),
"story-completion": ("DUPLICATE", "STORY / Story Completion / Default / Mobile", "Same screen"),
"search-no-results": ("DUPLICATE", "DISCOVERY / Search · Zero Results / Mobile", "Same screen"),
"creator-home-variant": ("OUTDATED", "DISCOVERY / For You / Default / Mobile", "Variant"),
"home-french": ("RESPONSIVE_VARIANT", "DISCOVERY / For You / Default / Mobile", "French language variant (locale), strings in i18n and per-screen COPY"),
"qr-object-entry": ("EXCLUDED", None, "Concept (object QR entry); needs physical-object content partners"),
"soft-branching": ("DUPLICATE", "STORY / Soft Branching / Perspective Shift / Mobile", "Same screen"),
"notification-settings": ("DUPLICATE", "PROFILE / Notification Settings / Mobile", "Same screen"),
"explore-empty": ("DUPLICATE", "DISCOVERY / Explore · Empty Filter / Mobile", "Same screen"),
'share-sheet': ('IMPLEMENTED', None, 'Share uses the system share sheet or copies the link; a custom sheet is intentionally not built'),
"creator-wizard-media": ("DUPLICATE", "CREATOR / Publish · Step 3 / Mobile", "Same screen"),
"moderation-appeal": ("EXCLUDED", None, "G4 gate: needs a named moderation policy owner"),
"guest-signup-prompt": ("EXCLUDED", None, "No guest mode"),
"button-loading-states": ("COMPONENT", None, "Button loading prop"),
"button-loading-action": ("COMPONENT", None, "Button loading prop"),
"button-disabled-form": ("COMPONENT", None, "Button disabled prop"),
"fr-story-entry": ("RESPONSIVE_VARIANT", "STORY / Story World / Default / Mobile", "French locale variant"),
"fr-settings": ("RESPONSIVE_VARIANT", "PROFILE / Settings Hub / Mobile", "French locale variant"),
"fr-signup": ("RESPONSIVE_VARIANT", "ONBOARDING / Sign Up / Default / Mobile", "French locale variant"),
"es-signup": ("RESPONSIVE_VARIANT", "ONBOARDING / Sign Up / Default / Mobile", "Spanish locale variant"),
"session-expired": ("DUPLICATE", "ONBOARDING / Session Expired / Default / Mobile", "Same state"),
"collection-detail": ("IMPLEMENTED", None, "CollectionDetailScreen"),
"search-results": ("DUPLICATE", "DISCOVERY / Search · Results / Mobile", "Same screen"),
"moderation-confirmed": ("STATE", None, "Moderation toast 'Approved/Rejected'"),
"media-playback-error": ("DUPLICATE", "STORY / Audio Player · Playback Failed / Mobile", "Same state"),
"creator-upload-progress": ("STATE", None, "MediaChaptersStep upload state"),
"library-empty": ("DUPLICATE", "LIBRARY / Empty · New User / Mobile", "Same state"),
"onboarding-welcome": ("DUPLICATE", "ONBOARDING / Splash / Default / Mobile", "Same screen"),
"06-20 — Collaboration Management": ("EXCLUDED", None, "Needs server accounts (collaboration)"),
"06-21 — Contributor Profile": ("EXCLUDED", None, "Needs collaboration accounts"),
"03-11 — Context Card Modal": ("DUPLICATE", "STORY / Context Card Modal / Mobile", "Same screen"),
"11-18 — Media Buffering State": ("DUPLICATE", "STORY / Audio Player · Buffering / Mobile", "Same state"),
"11-19 — Form Validation State": ("STATE", None, "TextField error states (forms.tsx)"),
"11-21 — Suspended User State": ("EXCLUDED", None, "Account enforcement waits on the G4 policy owner"),
"12-05 — Explorer (Français)": ("RESPONSIVE_VARIANT", "DISCOVERY / Explore · Default / Mobile", "French locale variant"),
"06-22 — Brock University Partnership": ("EXCLUDED", None, "Names a real organisation as a partner; not allowed without a signed agreement (D-12)"),
"12-06 — Bibliothèque (Français)": ("RESPONSIVE_VARIANT", "LIBRARY / Saved · Default / Mobile", "French locale variant"),
}
COMPONENTS = {
"Button": "seen/primitives Button", "Bottom Navigation": "seen/BottomNav", "Story Card": "StoryCard + seen/cards",
"Input Field": "seen/forms TextField", "Badge": "seen/primitives Badge", "Top Nav": "NavigationBar + seen/primitives TopBar",
"List Item": "seen/display ListItem", "Metric Card": "seen/primitives MetricCard", "Toggle": "seen/forms Toggle",
"Avatar": "seen/primitives Avatar", "Search Bar": "seen/forms SearchBar", "Notification Item": "NotificationsScreen item",
"Status Bar": "OS status bar (not an app component)", "bottom-navigation": "seen/BottomNav (duplicate of Bottom Navigation)",
}
